
package com.ca.devtest.lisabank.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EJB3UserControlBeanService", targetNamespace = "http://ejb3.examples.itko.com/", wsdlLocation = "http://localhost:9080/itkoExamples/EJB3UserControlBean?wsdl")
public class EJB3UserControlBeanService
    extends Service
{

    private final static URL EJB3USERCONTROLBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException EJB3USERCONTROLBEANSERVICE_EXCEPTION;
    private final static QName EJB3USERCONTROLBEANSERVICE_QNAME = new QName("http://ejb3.examples.itko.com/", "EJB3UserControlBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/itkoExamples/EJB3UserControlBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EJB3USERCONTROLBEANSERVICE_WSDL_LOCATION = url;
        EJB3USERCONTROLBEANSERVICE_EXCEPTION = e;
    }

    public EJB3UserControlBeanService() {
        super(__getWsdlLocation(), EJB3USERCONTROLBEANSERVICE_QNAME);
    }

    public EJB3UserControlBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EJB3USERCONTROLBEANSERVICE_QNAME, features);
    }

    public EJB3UserControlBeanService(URL wsdlLocation) {
        super(wsdlLocation, EJB3USERCONTROLBEANSERVICE_QNAME);
    }

    public EJB3UserControlBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EJB3USERCONTROLBEANSERVICE_QNAME, features);
    }

    public EJB3UserControlBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EJB3UserControlBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EJB3UserControlBean
     */
    @WebEndpoint(name = "EJB3UserControlBeanPort")
    public EJB3UserControlBean getEJB3UserControlBeanPort() {
        return super.getPort(new QName("http://ejb3.examples.itko.com/", "EJB3UserControlBeanPort"), EJB3UserControlBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EJB3UserControlBean
     */
    @WebEndpoint(name = "EJB3UserControlBeanPort")
    public EJB3UserControlBean getEJB3UserControlBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejb3.examples.itko.com/", "EJB3UserControlBeanPort"), EJB3UserControlBean.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EJB3USERCONTROLBEANSERVICE_EXCEPTION!= null) {
            throw EJB3USERCONTROLBEANSERVICE_EXCEPTION;
        }
        return EJB3USERCONTROLBEANSERVICE_WSDL_LOCATION;
    }

}
