
package com.ca.devtest.lisabank.wsdl;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EJB3AccountControlBean", targetNamespace = "http://ejb3.examples.itko.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EJB3AccountControlBean {


    /**
     * 
     * @param accountObj
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAccount", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.AddAccount")
    @ResponseWrapper(localName = "addAccountResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.AddAccountResponse")
    public String addAccount(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "accountObj", targetNamespace = "")
        Account accountObj);

    /**
     * 
     * @param accountId
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAccount", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.DeleteAccount")
    @ResponseWrapper(localName = "deleteAccountResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.DeleteAccountResponse")
    public boolean deleteAccount(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId);

    /**
     * 
     * @param accountId
     * @param amount
     * @param desc
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "depositMoney", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.DepositMoney")
    @ResponseWrapper(localName = "depositMoneyResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.DepositMoneyResponse")
    public String depositMoney(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId,
        @WebParam(name = "amount", targetNamespace = "")
        BigDecimal amount,
        @WebParam(name = "desc", targetNamespace = "")
        String desc);

    /**
     * 
     * @param accountId
     * @return
     *     returns com.ca.devtest.lisabank.wsdl.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.GetAccountResponse")
    public Account getAccount(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId);

    /**
     * 
     * @param accountId
     * @param transId
     * @return
     *     returns com.ca.devtest.lisabank.wsdl.Transaction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransaction", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.GetTransaction")
    @ResponseWrapper(localName = "getTransactionResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.GetTransactionResponse")
    public Transaction getTransaction(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId,
        @WebParam(name = "transId", targetNamespace = "")
        String transId);

    /**
     * 
     * @param accountId
     * @param from
     * @param to
     * @return
     *     returns java.util.List<com.ca.devtest.lisabank.wsdl.Transaction>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransactions", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.GetTransactions")
    @ResponseWrapper(localName = "getTransactionsResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.GetTransactionsResponse")
    public List<Transaction> getTransactions(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId,
        @WebParam(name = "from", targetNamespace = "")
        XMLGregorianCalendar from,
        @WebParam(name = "to", targetNamespace = "")
        XMLGregorianCalendar to);

    /**
     * 
     * @param username
     * @return
     *     returns java.util.List<com.ca.devtest.lisabank.wsdl.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAccounts", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.ListAccounts")
    @ResponseWrapper(localName = "listAccountsResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.ListAccountsResponse")
    public List<Account> listAccounts(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param amount
     * @param fromAccountId
     * @param toAccountId
     * @param desc
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferMoney", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.TransferMoney")
    @ResponseWrapper(localName = "transferMoneyResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.TransferMoneyResponse")
    public String transferMoney(
        @WebParam(name = "fromAccountId", targetNamespace = "")
        String fromAccountId,
        @WebParam(name = "toAccountId", targetNamespace = "")
        String toAccountId,
        @WebParam(name = "amount", targetNamespace = "")
        BigDecimal amount,
        @WebParam(name = "desc", targetNamespace = "")
        String desc);

    /**
     * 
     * @param accountId
     * @param amount
     * @param desc
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "withdrawMoney", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.WithdrawMoney")
    @ResponseWrapper(localName = "withdrawMoneyResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.WithdrawMoneyResponse")
    public String withdrawMoney(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId,
        @WebParam(name = "amount", targetNamespace = "")
        BigDecimal amount,
        @WebParam(name = "desc", targetNamespace = "")
        String desc);

}
