
package com.ca.devtest.lisabank.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EJB3UserControlBean", targetNamespace = "http://ejb3.examples.itko.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EJB3UserControlBean {


    /**
     * 
     * @param addressObject
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAddress", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.AddAddress")
    @ResponseWrapper(localName = "addAddressResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.AddAddressResponse")
    public String addAddress(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "addressObject", targetNamespace = "")
        Address addressObject);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns com.ca.devtest.lisabank.wsdl.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.AddUserResponse")
    public User addUser(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param userObject
     * @return
     *     returns com.ca.devtest.lisabank.wsdl.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserObject", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.AddUserObject")
    @ResponseWrapper(localName = "addUserObjectResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.AddUserObjectResponse")
    public User addUserObject(
        @WebParam(name = "userObject", targetNamespace = "")
        User userObject);

    /**
     * 
     * @param username
     * @param addressId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAddress", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.DeleteAddress")
    @ResponseWrapper(localName = "deleteAddressResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.DeleteAddressResponse")
    public boolean deleteAddress(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "addressId", targetNamespace = "")
        String addressId);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTestAccounts", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.DeleteTestAccounts")
    @ResponseWrapper(localName = "deleteTestAccountsResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.DeleteTestAccountsResponse")
    public boolean deleteTestAccounts();

    /**
     * 
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.DeleteUserResponse")
    public boolean deleteUser(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param addressId
     * @return
     *     returns com.ca.devtest.lisabank.wsdl.Address
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAddress", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.GetAddress")
    @ResponseWrapper(localName = "getAddressResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.GetAddressResponse")
    public Address getAddress(
        @WebParam(name = "addressId", targetNamespace = "")
        String addressId);

    /**
     * 
     * @param username
     * @return
     *     returns com.ca.devtest.lisabank.wsdl.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.GetUserResponse")
    public User getUser(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param username
     * @return
     *     returns java.util.List<com.ca.devtest.lisabank.wsdl.Address>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAddresses", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.ListAddresses")
    @ResponseWrapper(localName = "listAddressesResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.ListAddressesResponse")
    public List<Address> listAddresses(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @return
     *     returns java.util.List<com.ca.devtest.lisabank.wsdl.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listUsers", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.ListUsers")
    @ResponseWrapper(localName = "listUsersResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.ListUsersResponse")
    public List<User> listUsers();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param username
     * @return
     *     returns com.ca.devtest.lisabank.wsdl.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resetPassword", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.ResetPassword")
    @ResponseWrapper(localName = "resetPasswordResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.ResetPasswordResponse")
    public User resetPassword(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param userObject
     * @return
     *     returns com.ca.devtest.lisabank.wsdl.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.UpdateUserResponse")
    public User updateUser(
        @WebParam(name = "userObject", targetNamespace = "")
        User userObject);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validate", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.ValidateResponse")
    public boolean validate(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
