
package com.ca.devtest.lisabank.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TokenBean", targetNamespace = "http://ejb3.examples.itko.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TokenBean {


    /**
     * 
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteToken", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.DeleteToken")
    @ResponseWrapper(localName = "deleteTokenResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.DeleteTokenResponse")
    public boolean deleteToken(
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNewToken", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.GetNewToken")
    @ResponseWrapper(localName = "getNewTokenResponse", targetNamespace = "http://ejb3.examples.itko.com/", className = "com.ca.devtest.lisabank.wsdl.GetNewTokenResponse")
    public String getNewToken(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
