
package com.ca.devtest.lisabank.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TokenBeanService", targetNamespace = "http://ejb3.examples.itko.com/", wsdlLocation = "http://localhost:9080/itkoExamples/TokenBean?wsdl")
public class TokenBeanService
    extends Service
{

    private final static URL TOKENBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOKENBEANSERVICE_EXCEPTION;
    private final static QName TOKENBEANSERVICE_QNAME = new QName("http://ejb3.examples.itko.com/", "TokenBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/itkoExamples/TokenBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOKENBEANSERVICE_WSDL_LOCATION = url;
        TOKENBEANSERVICE_EXCEPTION = e;
    }

    public TokenBeanService() {
        super(__getWsdlLocation(), TOKENBEANSERVICE_QNAME);
    }

    public TokenBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOKENBEANSERVICE_QNAME, features);
    }

    public TokenBeanService(URL wsdlLocation) {
        super(wsdlLocation, TOKENBEANSERVICE_QNAME);
    }

    public TokenBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOKENBEANSERVICE_QNAME, features);
    }

    public TokenBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TokenBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TokenBean
     */
    @WebEndpoint(name = "TokenBeanPort")
    public TokenBean getTokenBeanPort() {
        return super.getPort(new QName("http://ejb3.examples.itko.com/", "TokenBeanPort"), TokenBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TokenBean
     */
    @WebEndpoint(name = "TokenBeanPort")
    public TokenBean getTokenBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejb3.examples.itko.com/", "TokenBeanPort"), TokenBean.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOKENBEANSERVICE_EXCEPTION!= null) {
            throw TOKENBEANSERVICE_EXCEPTION;
        }
        return TOKENBEANSERVICE_WSDL_LOCATION;
    }

}
